# Generated by Django 3.2.7 on 2021-09-17 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('situacao', models.BooleanField(default=True)),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('modificado_em', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField(default=0)),
                ('telefone', models.CharField(max_length=14)),
                ('cargo', models.CharField(max_length=30)),
                ('salario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('data_inicio', models.DateField()),
                ('criado_em', models.DateField(auto_now_add=True)),
                ('modificado_em', models.DateField(auto_now=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.departamento')),
            ],
        ),
    ]
