# Generated by Django 3.2.7 on 2021-09-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_remove_departamento_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
