# Generated by Django 3.2.7 on 2021-09-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_departamento_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='modificado_em',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='modificado_em',
        ),
    ]
